# Generated by Django 3.2.4 on 2021-08-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userType', models.CharField(max_length=8)),
                ('userGender', models.CharField(max_length=6)),
                ('userContactNo', models.CharField(max_length=10)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userAddress', models.CharField(max_length=300)),
                ('userCity', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=30)),
                ('userCreationTime', models.TimeField()),
                ('userCreationDate', models.DateField()),
                ('userBalance', models.IntegerField()),
                ('userStatus', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TblCustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerBalance', models.IntegerField()),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.tblregistration')),
            ],
        ),
    ]
