# Generated by Django 3.2.4 on 2021-08-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcustomerdetails',
            old_name='customerId',
            new_name='Customerid',
        ),
        migrations.RemoveField(
            model_name='tblregistration',
            name='userBalance',
        ),
        migrations.AlterField(
            model_name='tblregistration',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
