# Generated by Django 3.2.4 on 2021-08-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20210816_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSheetData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orderId', models.IntegerField()),
                ('orderAmount', models.IntegerField()),
                ('orderCreationTime', models.TimeField()),
                ('orderCreationDate', models.DateField()),
                ('amountPaid', models.IntegerField()),
                ('serialNo', models.IntegerField()),
                ('modificationDate', models.DateField()),
                ('orderStatus', models.CharField(max_length=15)),
                ('agentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.tblregistration')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.tblcustomerdetails')),
            ],
        ),
    ]
