# Generated by Django 3.2.4 on 2021-08-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_tblsheetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSheetDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uTime', models.TimeField()),
                ('uDate', models.DateField()),
                ('sheet', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
