# Generated by Django 3.2.4 on 2021-08-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_tblsheetdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsheetdata',
            name='orderCreationTime',
        ),
    ]
