# Generated by Django 3.2.4 on 2021-08-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_remove_tblsheetdata_ordercreationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsheetdata',
            name='amountPaid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tblsheetdata',
            name='serialNo',
            field=models.IntegerField(null=True),
        ),
    ]
