# Generated by Django 3.2.4 on 2021-08-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_auto_20210820_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsheetdata',
            name='amountPaid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblsheetdata',
            name='serialNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
